version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 30s
    #   retries: 20
  backend:
    depends_on:
      - db
      # db:
        # condition: service_healthy
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/app/media/
      - redoc:/app/docs/
  
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /result_build/
    volumes:
      - static:/result_build/
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/app/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  