# Generated by Django 5.0.4 on 2024-04-08 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ingredientsrepice',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repices.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repices.measuretypes'),
        ),
        migrations.AddField(
            model_name='repice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='repice',
            name='ingredients',
            field=models.ManyToManyField(through='repices.IngredientsRepice', to='repices.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientsrepice',
            name='repice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repices.repice'),
        ),
        migrations.AddField(
            model_name='tagsrepice',
            name='repice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repices.repice'),
        ),
        migrations.AddField(
            model_name='tagsrepice',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repices.tag'),
        ),
        migrations.AddField(
            model_name='repice',
            name='tags',
            field=models.ManyToManyField(through='repices.TagsRepice', to='repices.tag'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_following'),
        ),
    ]
