# Generated by Django 3.2.3 on 2024-05-03 18:45

import colorfield.fields
from django.db import migrations
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default=recipes.utils.get_rnd_hex_color, image_field=None, max_length=200, samples=None, unique=True, verbose_name='Цветовой код'),
        ),
    ]
