# Generated by Django 3.2.3 on 2024-04-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240420_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsRecipe',
            new_name='RecipeIngredient',
        ),
    ]
