# Generated by Django 3.2.3 on 2024-04-14 17:40

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Обязательное. 150 знаков или менее. Допустимы буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Forbidden symbol in username!', regex='^[\\w.@+-]+\\Z'), users.validators.check_me_name], verbose_name='Никнейм пользователя'),
        ),
    ]
