# Generated by Django 3.2.3 on 2024-04-26 18:53

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240415_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Обязательное. 150 знаков или менее. Допустимы буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Использованы запрещённые символы!', regex='^[\\w.@+-]+\\Z'), users.validators.check_me_name], verbose_name='Никнейм пользователя'),
        ),
    ]
